[request_definition]
r = sub, dom, ns, obj, act

[policy_definition]
p = sub, dom, ns, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.sub, r.dom) || g(r.sub, p.sub, "*")) \
    && (p.dom == "*" || r.dom == p.dom) \
    && (p.ns  == "*" || r.ns  == "*" || globMatch(r.ns,  p.ns)) \
    && (p.obj == "*" || r.obj == "*" || globMatch(r.obj, p.obj)) \
    && (p.act == "*" || r.act == p.act)
